# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368b3a897d7035f5b2dce12dfd5c5e083c01b685fc56ffba3b2046e98763ef639b2a8405fdb67a6cf166de7a531ab191b4bb824291940594810526d3ac8a377b

test:
  secret_key_base: cbe41dadb8312f02581dded7aee1319173a7fb4cae12918430fec961c0e541fdc41342e6f337d8342ac6da988fc71cd5bc91b9ffb886c89ee2c7cdd04387cc0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
